kumuluzee:
  name: catalog-services
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/CatalogsDS
    connection-url: jdbc:postgresql://192.168.99.100:5432/nejc
    username: postgres
    password: postgres
    max-pool-size: 20
  security:
      keycloak:
        json: '{
                "realm": "catalog-service",
                "bearer-only": true,
                "auth-server-url": "http://192.168.99.100:9080/auth",
                "ssl-required": "external",
                "resource": "catalog-service-api"
              }'

  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/CatalogsDS
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="catalogs">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                            <Socket name="logstash" host="5976162c-3680-400d-b980-26e8761dc4ef-ls.logit."
                            port="1798" protocol="tcp">
                                <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                            </Socket>
                        </Appenders>
                        <Loggers>
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info"/>
                                <AppenderRef ref="logstash" level="trace"/>
                            </Root>
                        </Loggers>
                    </Configuration>'
  metrics:
    web-instrumentation:
      - name: catalogs-endpoint
        url-pattern: /v1/catalogs/*
  openapi:
    ui:
      enabled: true
app-properties:
    external-services:
      enabled: false
    statistic-service:
      enabled: true
    healthy-service:
      enabled: true

# docker run -d -p 8082:8082 40850473/service-upload:0.0.5
#    docker run -d --name postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=nejc -p 5432:5432 postgres:10.5
#    docker run -d --name etcd-own -p 2379:2379  --volume=/tmp/etcd-data:/etcd-data quay.io/coreos/etcd:latest  /usr/local/bin/etcd --name my-etcd-1 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://0.0.0.0:2380 --initial-cluster my-etcd-1=http://0.0.0.0:2380    --initial-cluster-token my-etcd-token --initial-cluster-state new  --auto-compaction-retention 1 -cors="*"

# docker run -d --name postgres-nejc --listen-client-urls=http://0.0.0.0:5432 --advertise-client-urls=http://postgres/ -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=nejc -p 5432:5432 postgres:10.5

# docker run --name keycloak -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -d -p 9080:8080 jboss/keycloak