kumuluzee:
  name: users
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/CatalogsDS
#    TODO change URL to localhost!!!
    connection-url: jdbc:postgresql://192.168.99.100:5432/nejc
    username: postgres
    password: postgres
    max-pool-size: 20

# docker run -d -p 8082:8082 40850473/service-upload:0.0.5
#    docker run -d -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=nejc -p 5432:5432 postgres:10.5