apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - image: 40850473/service-catalog:0.1.9
        name: catalog
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: ibmcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_BASEURL
          value: http://35.240.79.227:8080
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://172.21.12.254:5432/nejc
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: catalog