apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - image: 40850473/service-upload:0.2.1
        name: upload
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: ibmcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_BASEURL
          value: http://35.240.79.227:8080
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://172.21.12.254:5432/nejc
        ports:
        - containerPort: 8082
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: upload
spec:
  type: NodePort
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: upload